### PR TITLE
Improve connection info file (previous network.json)

### LINKED ISSUE #52: Iterate on network.json
After some work on it, I think the spec must be improved 

Rename network.json -> connection.json

This file is important for the platform because it defines the parameters of the platform connection. Without this connection the platform is useless.

So the user must explicitly know if the connection is not configured as requested.

At platform boot, if:
 the file
 json object inside the file
 json fields
are badly formated. 

Then the platform must stop immediately and report an accurate error to the admin through the log file.

If the file is well formatted but some json field are missing, the platform must provide a default value for missing fields.

If the file does not exist, the platform has to start with the default connection parameters.

### PR DESCRIPTION
**Pull request by XdoctorwhoZ**
Working on the network.json file, I propose a new name to match all the requirement for this file. I also propose how the platform must handle error on this file.

### CODE REVIEW

**Comment by XdoctorwhoZ** [comment]
@wardru I took your comments and update the spec in the lastest commit  https://github.com/Panduza/panduza-dev-zone/pull/53/commits/bde0334d30b580640501251adabfec651ca3f9b9

Tell me if it is ok for you

**Comment by wardru** [comment]
Thanks, I am fixing some typos and after re-reading I have one last request/comment.

Here we expect the file to be at a specific location which is great. But do you agree we should also let the user provide a config file through a flag? Practical for quick testing or when the user has multiple config files.

I suggest `--config <filename>`.

If you agree I will add it as a requirement and push a commit

**Comment by XdoctorwhoZ** [comment]
> Thanks, I am fixing some typos and after re-reading I have one last request/comment.
> 
> Here we expect the file to be at a specific location which is great. But do you agree we should also let the user provide a config file through a flag? Practical for quick testing or when the user has multiple config files.
> 
> I suggest `--config <filename>`.
> 
> If you agree I will add it as a requirement and push a commit

I do agree 👍 (I also propose to append the retry timeout in this file, see the other issue. It make sense because it is also about the connection)

**Comment by wardru** [comment]
Pushed new commit with proposal, I approve and let you merge if you also approve

**Review by wardru — APPROVED** [review]

**Pull request merged**
